export const CatchError = (err) => { return { type: "Set_Err", data: err }}